name: Deploy to Pantheon Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Pantheon Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Add Pantheon SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
      - name: Push code to Pantheon Dev environment
        run: |
          git config --global user.name "Mustakim Farooqui"
          git config --global user.email ${{ secrets.PANTHEON_ACCOUNT}}

          git push ssh://codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in:2222/~/repository.git dev:master --force
      - name: Install Terminus and Authenticate
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Run database updates
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- updatedb -y

      - name: Import config
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- config-import -y

      - name: Clear cache
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- cr
