name: Deploy to Pantheon Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Pantheon Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, gd, curl, json, zip
          tools: composer, drush

      - name: Add SSH Key for Pantheon
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.9/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/terminus

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }} --email=${{ secrets.PANTHEON_ACCOUNT }}

      - name: Push code to Pantheon Dev environment
        run: |
          git remote add pantheon ssh://codeserver.dev.${{ secrets.PANTHEON_SITE }}@codeserver.dev.${{ secrets.PANTHEON_SITE }}.drush.in:2222/~/repository.git || true
          git push pantheon dev:master --force

      - name: Import config
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- config-import -y

      - name: Run database updates
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- updatedb -y

      - name: Clear cache
        run: terminus drush ${{ secrets.PANTHEON_SITE }}.dev -- cr